### ISSUE TITLE
Package dependencies

### ISSUE THREAD

**Issue by lukecampbell** [SciTools/cf-units#54]
I've been troubleshooting a bunch of tox issues for a project that uses cf_units and I found where the source of the trouble is. cf_units defines the project dependencies in a conda requirements file but not in the setup.py file

Specifically the dependency that's giving me grief is six.

Could you also include the project dependencies in the setup.py file? It might be as simple as

``` python
install_requires = [line.strip() for line in open('conda_requirements.txt')]
```

**Comment by ocefpaf** [comment]
I though that was already solved a long time ago. Sorry for that! Preparing a PR now.

Edit: bare in mind that there are no wheels for `udunits2` at PyPI. So a `pip install` will be always incomplete.

**Comment by lukecampbell** [comment]
Yeah, on that note...

**Comment by lukecampbell** [comment]
I was going to make a new issue but I can't find where in the code it happens or generate an example quickly. But if you pip install cf_units without udunits installed it will install but you get a runtime error of sort. It would be really awesome if you could wrap the first occurrence of a reference to udunits2 with an exception handler that prints "Maybe you forgot libudunits2 ?"

instead of "undefined symbol CV_Float" or whatever it is

**Comment by ocefpaf** [comment]
I have an unfinised  PR for that since https://github.com/ioos/compliance-checker/issues/265#issuecomment-215791057 happened. I just need some days with 30 hours and weeks with 10 days to finish :wink:

**Comment by lukecampbell** [comment]
yeah, me too...

**Comment by rhattersley** [comment]
[Looks like](https://github.com/SciTools/cf_units/pull/56) you found a 30-hour day after all ... well done! :wink:
